Implement report.rs component
CDCgov/ixa pull request #28
Opened 2024-08-27 13:13 UTC by ranya-cfa

Work in progress

2024-08-27 19:00 UTC, ranya-cfa commented
"".to_string() giving cargo clippy error

2024-08-27 21:27 UTC, k88hudson-cfa requested changes

2024-08-27 21:27 UTC, k88hudson-cfa commented on src/report.rs
> +        println!("Generated filename: {}", filename.display());
Remove this println

2024-08-27 21:27 UTC, k88hudson-cfa commented on src/report.rs
> +    fn generate_filename(&mut self, short_name: &str) -> PathBuf {
Rather than making this part of the trait extension, can you make this a private helper function?

2024-08-27 21:27 UTC, k88hudson-cfa commented on src/report.rs
> +    fn init_reports(&mut self, file_prefix: Option<&str>, directory: Option<&str>) {
let's call this `set_report_options`

2024-08-28 16:15 UTC, k88hudson-cfa requested changes

2024-08-28 16:15 UTC, k88hudson-cfa commented on src/report.rs
> +                name: "Test1".to_string(),
Can you test something with a Comma, like "Test,1"

2024-08-28 16:15 UTC, k88hudson-cfa commented on src/report.rs
> +            writer.serialize(record)?;
You should be testing the output of the library itself, not constructing a writer

2024-08-28 16:15 UTC, k88hudson-cfa commented on src/report.rs
> +        Ok(())
Is this intended?

2024-08-29 13:22 UTC, k88hudson-cfa commented on Cargo.toml
> +tempfile = "3.3"
Should be dev dependencies

2024-08-29 16:19 UTC, k88hudson-cfa commented on src/report.rs
> +    /// The options can be assigned to the config that is returned from this function
```suggestion
    /// Returns a `ConfigReportOptions` object which has setter methods for report configuration
```

2024-08-29 16:21 UTC, k88hudson-cfa commented on src/report.rs
> +    /// Note that you will need to call the method with the appropriate report type
```suggestion
    /// Write a new row to the appropriate report file
```

2024-08-29 16:21 UTC, k88hudson-cfa commented on src/report.rs
> +    /// The report type name is used for file naming to distinguish what data each
```suggestion
    /// The `short_name` is used for file naming to distinguish what data each
```

2024-08-29 16:24 UTC, k88hudson-cfa approved these changes
LGTM

2024-08-29 16:24 UTC, merged