Example of time-varying rates
CDCgov/ixa pull request #54
Opened 2024-10-01 20:49 UTC by ChiragKumar9

Example of how to model time-varying rates (foi and recovery) in `ixa`. Specific consideration given to the math of how to do demonstrate the ergonomics of doing this in Rust.

WIP.

2024-10-29 20:14 UTC, confunguido requested changes
I think this mostly looks good. I had one comment about person property initialization. I'm not super sure about the rejection sampling. Is there a better way to do that? I would like to think of other examples that require rejection sampling that are more common in our models. It would also be nice to try an example with time-varying infectiousness (or FOI) that's not seasonal.

2024-10-30 19:51 UTC, ChiragKumar9 commented on examples/time-varying-infection/population_loader.rs
> +define_person_property_with_default!(InfectionTime, Option<f64>, None);
Thanks, Guido! Yeah you're totally right -- I changed this.

2024-10-31 18:29 UTC, confunguido commented
This looks fine from my perspective.

2024-10-31 18:29 UTC, confunguido approved these changes

2024-11-04 17:50 UTC, merged